// Define all product categories into category groups
export const freshCategory = [
  "eggs",
  "fruit",
  "fresh-vegetables",
  "salads-coleslaw",
  "bread",
  "bread-rolls",
  "specialty-bread",
  "bakery-cakes",
  "bakery-desserts",
];

export const chilledCategory = [
  "milk",
  "cream",
  "yoghurt",
  "butter",
  "cheese",
  "salami",
  "dips-hummus",
  "other-deli-foods",
];

export const meatCategory = [
  "beef-lamb",
  "chicken",
  "ham",
  "bacon",
  "pork",
  "patties-meatballs",
  "sausages",
  "deli-meats",
  "meat-alternatives",
  "seafood",
  "salmon",
];

export const frozenCategory = [
  "ice-cream",
  "ice-blocks",
  "pastries-cheesecake",
  "frozen-chips",
  "frozen-vegetables",
  "frozen-fruit",
  "frozen-seafood",
  "pies-sausage-rolls",
  "pizza",
  "other-savouries",
];

export const pantryCategory = [
  "rice",
  "noodles",
  "pasta",
  "beans-spaghetti",
  "canned-fish",
  "canned-fruit",
  "canned-meat",
  "soup",
  "cereal",
  "spreads",
  "baking",
  "sauces",
  "oils-vinegars",
  "world-foods",
  "herbs-spices",
];

export const snacksCategory = [
  "chocolate",
  "boxed-chocolate",
  "chips",
  "crackers",
  "biscuits",
  "muesli-bars",
  "nuts-bulk-mix",
  "sweets-lollies",
  "other-snacks",
];

export const drinksCategory = [
  "long-life-milk",
  "black-tea",
  "green-tea",
  "herbal-tea",
  "drinking-chocolate",
  "coffee",
  "soft-drinks",
  "energy-drinks",
  "juice",
  "water",
];

export const beerWineCategory = ["beer", "craft-beer", "wine"];

export const petsCategory = [
  "cat-food",
  "cat-treats",
  "dog-food",
  "dog-treats",
];

export const titledCategoryGroups = [
  { title: "Fresh Foods", categories: freshCategory },
  { title: "Chilled", categories: chilledCategory },
  { title: "Meat", categories: meatCategory },
  { title: "Frozen", categories: frozenCategory },
  { title: "Pantry", categories: pantryCategory },
  { title: "Snacks", categories: snacksCategory },
  { title: "Drinks", categories: drinksCategory },
  { title: "Beer & Wine", categories: beerWineCategory },
  { title: "Pets", categories: petsCategory },
];

export const titledCategories: Record<string, string> = {
  eggs: "Eggs",
  fruit: "Fruit",
  "fresh-vegetables": "Fresh Vegetables",
  "salads-coleslaw": "Salads & Coleslaw",
  bread: "Bread",
  "bread-rolls": "Bread Rolls",
  "specialty-bread": "Wraps",
  "bakery-cakes": "Bakery Cakes",
  "bakery-desserts": "Bakery Desserts",
  milk: "Fresh Milk",
  "long-life-milk": "Long Life & Plant Milk",
  cream: "Cream",
  yoghurt: "Yoghurt",
  butter: "Butter",
  cheese: "Cheese",
  salami: "Salami",
  "other-deli-foods": "Other Deli Foods",
  "dips-hummus": "Dips & Hummus",
  "beef-lamb": "Beef & Lamb",
  chicken: "Chicken",
  ham: "Ham",
  bacon: "Bacon",
  pork: "Pork",
  "patties-meatballs": "Patties & Meatballs",
  sausages: "Sausages",
  "deli-meats": "Deli Meats",
  "meat-alternatives": "Meat Alternatives",
  seafood: "Seafood",
  salmon: "Salmon",
  "ice-cream": "Ice Cream",
  "ice-blocks": "Ice Blocks",
  "pastries-cheesecake": "Pastries & Cheesecake",
  "frozen-chips": "Frozen Chips",
  "frozen-vegetables": "Frozen Vegetables",
  "frozen-fruit": "Frozen Fruit",
  "frozen-seafood": "Frozen Seafood",
  "pies-sausage-rolls": "Pies & Sausage Rolls",
  pizza: "Pizza",
  "other-savouries": "Other Savouries",
  rice: "Rice",
  noodles: "Noodles",
  pasta: "Pasta",
  "beans-spaghetti": "Beans & Spaghetti",
  "canned-fish": "Canned Fish",
  "canned-fruit": "Canned Fruit & Veg",
  "canned-meat": "Canned Meat",
  soup: "Soup",
  cereal: "Cereal",
  spreads: "Spreads",
  baking: "Baking",
  sauces: "Sauces",
  "oils-vinegars": "Oils & Vinegars",
  "world-foods": "World Foods",
  "herbs-spices": "Herbs & Spices",
  chocolate: "Chocolate",
  "boxed-chocolate": "Boxed Chocolate",
  chips: "Chips",
  crackers: "Crackers",
  biscuits: "Biscuits",
  "muesli-bars": "Muesli Bars",
  "nuts-bulk-mix": "Nuts & Bulk Mix",
  "sweets-lollies": "Sweets & Lollies",
  "other-snacks": "Other Snacks",
  "black-tea": "Black Tea",
  "green-tea": "Green Tea",
  "herbal-tea": "Herbal Tea",
  "drinking-chocolate": "Drinking Chocolate",
  coffee: "Coffee",
  "soft-drinks": "Soft Drinks",
  "energy-drinks": "Energy Drinks",
  juice: "Juice",
  water: "Water",
  beer: "Beer",
  "craft-beer": "Craft Beer",
  wine: "Wine",
  "cat-food": "Cat Food",
  "cat-treats": "Cat Treats",
  "dog-food": "Dog Food",
  "dog-treats": "Dog Treats",
};

// Combine all category groups into one big array.
export const allCategoryNames = freshCategory.concat(
  chilledCategory,
  meatCategory,
  frozenCategory,
  pantryCategory,
  snacksCategory,
  drinksCategory,
  beerWineCategory,
  petsCategory
);
