name: build-test-deploy-to-s3
permissions:
  contents: read
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env File
        run: |
          touch .env
          echo "COSMOS_CONSTRING=${{ secrets.COSMOS_CONSTRING }}" >> .env
          echo "COSMOS_CONTAINER=${{ secrets.COSMOS_CONTAINER }}" >> .env
          echo "COSMOS_DBNAME=${{ secrets.COSMOS_DBNAME }}" >> .env
          echo "IMAGES_PATH=${{ secrets.IMAGES_PATH }}" >> .env
          echo "TZ=Pacific/Auckland" >> .env

      - name: NPM Build and Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy to AWS S3
        run: aws s3 sync ./out s3://${{ vars.S3_BUCKET }} --quiet --delete
