name: build-and-deploy-to-s3
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Create .env file
        run: |
          touch .env
          echo "COSMOS_CONSTRING=${{ secrets.COSMOS_CONSTRING }}" >> .env
          echo "COSMOS_CONTAINER=${{ secrets.COSMOS_CONTAINER }}" >> .env
          echo "COSMOS_DBNAME=${{ secrets.COSMOS_DBNAME }}" >> .env
          echo "IMAGES_PATH=${{ secrets.IMAGES_PATH }}" >> .env
          echo "TZ=Pacific/Auckland" >> .env

      - run: npm run build

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - run: aws s3 sync ./out s3://${{ vars.S3_BUCKET }}
